// Media generation — Gemini multimodal on Vertex produces an illustration only
// when no open-licensed photo was found (e.g. long-extinct species). Output is
// saved via the existing storage layer and always tagged as AI-generated. Audio
// is NOT generated here: real recordings come from the Xeno-canto connector;
// fabricating what an extinct animal "sounded like" is out of scope.
import { generateText } from "ai";
import { nanoid } from "nanoid";
import { mediaModel } from "./provider.js";
import { llmConfigured } from "./provider.js";
import { estimateCostCents, totalTokens, type TokenUsage } from "./cost.js";
import { meter, RunBudget } from "../budget.js";
import { save } from "../../lib/storage.js";
import { db, schema } from "../../db/client.js";
import type { SpeciesRecord } from "../types.js";

interface GeneratedFile {
  base64?: string;
  uint8Array?: Uint8Array;
  mediaType?: string;
  mimeType?: string;
}

/** Returns a stored image URL, or null if generation is unavailable/failed. */
export async function generateSpeciesImage(
  species: SpeciesRecord,
  budget: RunBudget,
  createdBy?: string,
): Promise<string | null> {
  if (!llmConfigured()) return null;
  try {
    const prompt =
      `A natural-history illustration of ${species.name} (${species.scientific}), ` +
      `scientifically accurate, neutral museum-plate style, plain background. ` +
      `This is an illustration, not a photograph.`;

    const result = await generateText({ model: mediaModel(), prompt });
    const cost = estimateCostCents("media", result.usage as TokenUsage);
    budget.charge(cost);
    await meter("vertex-gemini", { calls: 1, tokens: totalTokens(result.usage as TokenUsage), costCents: cost });

    // The AI SDK exposes generated binary parts on `.files`.
    const files = ((result as unknown as { files?: GeneratedFile[] }).files) ?? [];
    const img = files.find((f) => (f.mediaType || f.mimeType || "").startsWith("image/"));
    if (!img) return null;

    const buf = img.uint8Array
      ? Buffer.from(img.uint8Array)
      : img.base64
        ? Buffer.from(img.base64, "base64")
        : null;
    if (!buf) return null;

    const saved = await save(buf);
    await db.insert(schema.media).values({
      id: saved.id,
      kind: saved.kind,
      mime: saved.mime,
      sizeBytes: saved.size,
      url: saved.url,
      originalName: `${species.scientific ?? species.name ?? nanoid()}.gen`,
      createdBy: createdBy ?? null,
      generatedBy: "gemini",
      license: "AI-generated illustration (Gemini)",
      attribution: "Illustration generated by Google Gemini — not a photograph",
    });
    return saved.url;
  } catch {
    // Media generation is best-effort; a missing image just means a fallback.
    return null;
  }
}
